### ISSUE TITLE
Could you release the code?

### ISSUE THREAD

**Issue by zhoufengfan** [Felix-Petersen/fairness-post-processing#1]
Thanks a lot.

**Comment by Felix-Petersen** [comment]
Thanks for your interest! Right now, I am quite busy, but I will release the code soon, i.e., in about a month.

**Comment by Fecsio** [comment]
Hi, 
I'm really interested in your work and would really like to see its implementation for academic purposes. Any chance on releasing it soon?

**Comment by Felix-Petersen** [comment]
I am sorry, I thought that I had already uploaded it. I will do my best to publish it on the weekend!

Best regards,

Felix

**Comment by Felix-Petersen** [comment]
@zhoufengfan @Fecsio I uploaded the code! Don't hesitate to ask if you have any questions.

Best 
Felix
